# Generated by Django 4.0.6 on 2022-12-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_reviewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='userprofile',
        ),
    ]
