# Generated by Django 4.0.6 on 2022-12-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
