# Generated by Django 4.0.6 on 2022-10-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_quantity_cartitem_quality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
    ]
