# Generated by Django 4.0.6 on 2022-11-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_variation_category'),
        ('cart', '0004_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variation',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
